name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build for Linux x86_64
        run: make
      - name: Package artifact
        run: |
          ls
          tar -czf waed-linux-x86_64.tar.gz ./waed
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: waed-linux-x86_64
          path: waed-linux-x86_64.tar.gz

  build-linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build for Linux ARM64
        run: make
      - name: Package artifact
        run: tar -czf waed-linux-arm64.tar.gz ./waed
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: waed-linux-arm64
          path: waed-linux-arm64.tar.gz

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build for macOS
        run: make
      - name: Package artifact
        run: tar -czf waed-macos-arm64.tar.gz ./waed
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: waed-macos
          path: waed-macos-arm64.tar.gz

  release:
    needs: [build-linux-x86_64, build-linux-arm64, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          generate_release_notes: true